# Generated by Django 4.1.7 on 2023-04-10 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pages',
            old_name='url',
            new_name='content',
        ),
    ]
